### ISSUE TITLE
What is the correct sampling rate (frequency) of ECG in SHHS1?

### ISSUE THREAD

**Issue by wenh06** [nsrr/shhs-data-dictionary#1105]
When I loaded some EDF file in SHHS1 using pyedflib, and called `file_info_long()`, it produced
"...
label: ECG fs: 125 nsamples 3948750
..."
However, on [this page](https://sleepdata.org/datasets/shhs/pages/10-montage-and-sampling-rate-information-shhs1.md), there is a "265" in the `sampling rate` cell of ECG in the table, while "125" is in the `hardware filters` cell. In the corresponding webpage of SHHS2, these two values are "250"/"256" and "High pass 0.15".

I guess sampling rate and sampling frequency are the same thing. And I think that 125 Hz is the correct value, but that webpage makes me confused.

**Comment by mrueschman** [comment]
Thanks! I corrected the SHHS1 montage information to correctly reflect a 125 Hz sampling rate for ECG.

https://sleepdata.org/datasets/shhs/pages/10-montage-and-sampling-rate-information-shhs1.md
